FROM nginx:alpine

# Hapus settingan bawaan Nginx yang standar
RUN rm /etc/nginx/conf.d/default.conf

# Masukkan settingan (nginx.conf) buatan kita sendiri
COPY nginx.conf /etc/nginx/conf.d/default.conf
